
% Salvar em um arquivo excel


% Load 1
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_1_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_1_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_1_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_1_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_1_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_1_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.Q_C);

% Load 3
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_3.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_3_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_3.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_3_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_3.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_3_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_3.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_3_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_3.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_3_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_3.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_3_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_3.Q_C);

% Load 4
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_4.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_4_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_4.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_4_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_4.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_4_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_4.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_4_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_4.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_4_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_4.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_4_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_4.Q_C);

% Load 5
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_5.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_5_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_5.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_5_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_5.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_5_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_5.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_5_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_5.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_5_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_5.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_5_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_5.Q_C);

% Load 6
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_6.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_6_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_6.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_6_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_6.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_6_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_6.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_6_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_6.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_6_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_6.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_6_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_6.Q_C);

% Load 8
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_8.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_8_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_8.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_8_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_8.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_8_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_8.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_8_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_8.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_8_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_8.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_8_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_8.Q_C);

% Load 9
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_9.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_9_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_9.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_9_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_9.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_9_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_9.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_9_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_9.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_9_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_9.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_9_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_9.Q_C);

% Load 10
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_10.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_10_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_10.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_10_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_10.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_10_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_10.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_10_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_10.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_10_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_10.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_10_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_10.Q_C);

% Load 11
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_11.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_11_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_11.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_11_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_11.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_11_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_11.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_11_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_11.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_11_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_11.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_11_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_11.Q_C);

% Load 13
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_13.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_13_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_13.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_13_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_13.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_13_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_13.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_13_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_13.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_13_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_13.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_13_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_13.Q_C);

% Load 14
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_14.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_14_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_14.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_14_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_14.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_14_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_14.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_14_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_14.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_14_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_14.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_14_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_14.Q_C);

% Load 15
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_15.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_15_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_15.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_15_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_15.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_15_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_15.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_15_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_15.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_15_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_15.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_15_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_15.Q_C);

% Load 16
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_16.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_16_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_16.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_16_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_16.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_16_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_16.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_16_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_16.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_16_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_16.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_16_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_16.Q_C);

% Load 17
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_17.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_17_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_17.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_17_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_17.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_17_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_17.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_17_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_17.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_17_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_17.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_17_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_17.Q_C);

% Load 18
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_18.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_18_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_18.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_18_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_18.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_18_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_18.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_18_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_18.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_18_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_18.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_18_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_18.Q_C);

% Load 19
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_19.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_19_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_19.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_19_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_19.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_19_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_19.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_19_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_19.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_19_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_19.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_19_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_19.Q_C);

% Load 21
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_21.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_21_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_21.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_21_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_21.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_21_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_21.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_21_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_21.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_21_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_21.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_21_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_21.Q_C);

% Load 23
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_23.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_23_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_23.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_23_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_23.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_23_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_23.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_23_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_23.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_23_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_23.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_23_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_23.Q_C);

% Load 25
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_25.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_25_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_25.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_25_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_25.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_25_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_25.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_25_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_25.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_25_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_25.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_25_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_25.Q_C);

% Load 26
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_26.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_26_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_26.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_26_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_26.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_26_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_26.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_26_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_26.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_26_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_26.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_26_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_26.Q_C);

% Load 29
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_29.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_29_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_29.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_29_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_29.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_29_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_29.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_29_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_29.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_29_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_29.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_29_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_29.Q_C);

% Load 31
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.P_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_31.P_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_31_P_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.P_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.P_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_31.P_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_31_P_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.P_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.P_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_31.P_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_31_P_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.P_C);

Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.Q_A = Coleta_Dados_OpenDSS.Perfil_Carga.Load_31.Q_A(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_31_Q_A.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.Q_A);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.Q_B = Coleta_Dados_OpenDSS.Perfil_Carga.Load_31.Q_B(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_31_Q_B.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.Q_B);
Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.Q_C = Coleta_Dados_OpenDSS.Perfil_Carga.Load_31.Q_C(1:length(Coleta_Dados_OpenDSS.Perfil_Carga.Load_1.P_A)/1440:(end)); dlmwrite("C:\Users\hugo1\Desktop\Projeto\Circuito_teste\Circuito_OpenDSS\LoadShapes\Load_31_Q_C.txt",Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_31.Q_C);



% plot(Coleta_Dados_OpenDSS.Ajustados.Perfil_Carga.Load_1.P_A)
